image: docker:19.03.11

services:
  - docker:19.03.11-dind

# We don't have to cache anything this pipeline.
cache: {}

build:
  stage: build
  script:
    - docker build -t elypia/alexis-discord:latest -f Dockerfile .
